### ISSUE TITLE
A runtime error about loss_g.backward()

### ISSUE THREAD

**Issue by DAYceng** [9310gaurav/ali-pytorch#6]
Hi，I tried to run these programs 
the runtime environment is：torch1.8.1+cu111、python3.7
The graphics card I use is RTX3060
but got an error：
```
D:\pycharm_env\ali-pytorch-master\lib\site-packages\torch\nn\functional.py:1709: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
Traceback (most recent call last):
  File "D:/code/ali-pytorch-master/main.py", line 163, in <module>
    loss_g.backward()
  File "D:\pycharm_env\ali-pytorch-master\lib\site-packages\torch\tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "D:\pycharm_env\ali-pytorch-master\lib\site-packages\torch\autograd\__init__.py", line 147, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1, 1024, 1, 1]] is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```

I have tried the following：
1、**Change `nn.LeakyReLU(inplace=True)` to `nn.LeakyReLU(inplace=False)`**
it doesn't work
2、**Move the optimizerD.step() operation to the back**
like this
```
#loss_g.data[0]
        if loss_g.item() < 3.5:
            optimizerD.zero_grad()
            loss_d.backward(retain_graph=True)
            #optimizerD.step() # Why is it okay to update before the generator?

        optimizerG.zero_grad()
        loss_g.backward()
        optimizerD.step()
        optimizerG.step()
```
Although there is no error in the second method, during the training process, fake images cannot be generated well, which is obviously incorrect.

do you have any good advice?

**Comment by ChangWenhan** [comment]
Hi, I solved the problem~
This problem is simply due to the wrong path.

First you must manually create the folder where the images and models will be stored. I modified this part of the code:

`
parser.add_argument('--save_image_dir', default='/home/amax/CODE/ali-pytorch-master/image')
`

Also you need to modify the codes of 151-152 and 157-159, just like this:

turn `vutils.save_image(d_fake.cpu().data[:16, ], './%s/fake.png' % (opt.save_image_dir))`
to    `vutils.save_image(d_fake.cpu().data[:16, ], '%s/fake.png' % (opt.save_image_dir))`

As you can see we just removed all the `./` to solve it, this problem is very annoying.
